### PR TITLE
Compiler Error Swift.Collection required

### PR DESCRIPTION
**Pull request by Bino90**
## Checklist
- [x] All tests are passed.  
- [x] Searched existing pull requests for ensure not duplicated.  

## Description
Swift Compiler Error because of Collection Naming issue

## Motivation and Context
Release Build ERROR Swift Compiler!

### CODE REVIEW

**Review by grangej — APPROVED** [review]
Yes this is blocking Xcode 11.4

**Comment by Bino90** [comment]
Please merge and make a new version :)

**Comment by ra1028** [comment]
Thanks @Bino90 

I don't know under what circumstances this error occurs, but I'm merging and releasing a new version as there are no bad effects from this fix.

**Comment by ikesyo** [comment]
Looks like this only occurs when optimization is enabled (Release build). I was facing the same problem.

**Comment by Bino90** [comment]
Yeah correct - this error only occurs when optimization is enabled

**Comment by qasim** [comment]
@ra1028 thank you for merging 🙌 can you push a new tag for projects to point to? ☺️

**Pull request merged**
